---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for a list of all hooks
repos:
  ### GENERAL ###
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-json
        exclude: |
          (?x)^(
              .devcontainer/devcontainer.json|
              tsconfig.json
          )$
      - id: check-toml
      - id: check-xml
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
        exclude: |
          (?x)^(
              .cruft.json|
          )$
  # opinionated code formatter for all things frontend (also includes Markdown, JSON, YAML)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.27.1
    hooks:
      - id: yamllint
        args: [-c=.yamllint]

  ### JAVA(SCRIPT) ###
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.19.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.19.0
          - eslint-plugin-jest@26.6.0
          - "@typescript-eslint/parser@5.30.6"
          - "@typescript-eslint/eslint-plugin@5.30.6"
          - eslint-plugin-github@4.3.6
          - eslint-plugin-prettier@4.2.1
          - eslint-plugin-eslint-comments@3.2.0
          - eslint-plugin-filenames@1.3.2
          - eslint-plugin-i18n-text@1.0.1
          - eslint-plugin-no-only-tests@2.6.0
          - eslint-plugin-import@2.26.0

default_language_version:
  python: python3
ci:
  autofix_commit_msg: |
    chore(pre-commit): auto fixes from hooks :rotating_light:

    for more information, see https://pre-commit.ci
  autoupdate_commit_msg: |
    chore(pre-commit): autoupdate :arrow_up:

    TIP: you can trigger a re-run on a pull request by commenting `pre-commit.ci run` (must appear on a line by itself)
exclude: ".idea"
