---
name: build self-contained README
permissions:
  pages: write
  contents: write
"on":
  push:

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: check out the codebase
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3

      - name: setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.0"

      - name: install Asciidoctor
        run: gem install --no-document asciidoctor asciidoctor-reducer rouge coderay

      - name: Generate README.adoc using ascidoctor-reducer.
        run: asciidoctor-reducer README.orig.adoc -o README.adoc

      - name: Commit generated README.
        uses: stefanzweifel/git-auto-commit-action@49620cd3ed21ee620a48530e81dba0d139c9cb80 # tag=v4
        with:
          commit_message: "docs: reduce README.orig.adoc \n ${{ github.event.head_commit.message }}"
          file_pattern: README.adoc
          disable_globbing: true

      - name: Generate HTML
        run: asciidoctor --backend=html5 --destination-dir docs --out-file index.html README.adoc

      - name: Deploy HTML to GitHub Pages (when branch is master).
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # tag=v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/
        if: github.ref == 'refs/heads/master'
